name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      scylla:
        image: scylladb/scylla:5.2.0
        ports:
          - 9042:9042
        options: >-
          --health-cmd "nodetool status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_CFG_NODE_ID: 0
          KAFKA_CFG_PROCESS_ROLES: controller,broker
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          ALLOW_PLAINTEXT_LISTENER: yes
        options: >-
          --health-cmd "kafka-topics.sh --bootstrap-server localhost:9092 --list"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 30s

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for Kafka and Cassandra to be ready
        run: |
          sudo apt-get update && sudo apt-get install -y curl python3 wget python3-pip
          
          sleep 30
          docker exec scylla cqlsh -e "CREATE KEYSPACE IF NOT EXISTS user_audit WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};"
          docker exec scylla cqlsh -e "CREATE TABLE IF NOT EXISTS user_audit.outbox (id uuid PRIMARY KEY, value text);"
          
          wget -q https://downloads.apache.org/kafka/3.7.0/kafka_2.13-3.7.0.tgz
          tar -xzf kafka_2.13-3.7.0.tgz
          export PATH=$PATH:$(pwd)/kafka_2.13-3.7.0/bin
          
          for i in {1..30}; do
            if kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1; then
              break
            fi
            sleep 5
          done

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Run Outbox tests first
        run: mvn test -Dtest=OutboxIntegrationTest
        env:
          SPRING_PROFILES_ACTIVE: test
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
          cassandra.host: localhost
          cassandra.port: 9042

      - name: Run all tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
          cassandra.host: localhost
          cassandra.port: 9042